import xxhash = xxhash%lib{xxhash}

./: lib{lz4}: lib/{c h}{lz4}
{
    cc.export.poptions = "-I$src_base/lib"
}

./: lib{lz4hc}: lib/{c h}{lz4hc} lib{lz4}
{
    cc.export.poptions = "-I$src_base/lib"
    cc.export.libs = lib{lz4}
}

./: lib{lz4frame}: lib/{c h}{lz4frame} lib{lz4hc} $xxhash
{
    cc.export.poptions = "-I$src_base/lib"
    cc.export.libs = lib{lz4hc} $xxhash
}
