import xxhash = xxhash%lib{xxhash}

lib{lz4}: lib/{c h}{lz4 lz4hc lz4frame} $xxhash
{
    cc.export.poptions = "-I$src_base/lib"
    cc.export.libs = $xxhash
}

if ($c.target.class == 'windows')
{
    {hbmis objs}{*}: c.poptions += "-DLZ4_DLL_EXPORT"
    libs{lz4}: cc.export.poptions += "-DLZ4_DLL_IMPORT"
}
