import libs  = lz4%lib{lz4}
import libs += lz4%lib{lz4hc}
import libs += lz4%lib{lz4frame}

./: exe{fuzzer}: c{fuzzer} $libs
exe{fuzzer}: test.options = '-i2048'

./: exe{frametest}: c{frametest} $libs
exe{frametest}: test.options = '-i2048'
