import libs = lz4%liba{lz4}

./: exe{fuzzer}: c{fuzzer} h{util platform} $libs
exe{fuzzer}: test.options = '-i2048'

./: exe{frametest}: c{frametest} h{util platform} $libs
exe{frametest}: test.options = '-i2048'
