libs =
#import libs += libhello%lib{hello}

exe{lz4}: {h c}{**} $libs programs/testscript

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx" "-I$src_pfx"
